kind: Deployment
apiVersion: apps/v1
metadata:
  name: anathema-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anathema-client
  template:
    metadata:
      labels:
        app: anathema-client
    spec:
      containers:
      - name: anathema-client
        image: docker.io/kevinsqi/anathema-client:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: anathema-client-loadbalancer
  labels:
    app: anathema-client
spec:
  type: LoadBalancer
  selector:
    app: anathema-client
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      nodePort: 31000
